services:
  postgres:
    image: postgres:18
    container_name: postgres
    restart: unless-stopped
    environment:
      # Bootstrap super admin (used only for first init)
      POSTGRES_USER: ${SUPER_ADMIN_USER}
      POSTGRES_PASSWORD: ${SUPER_ADMIN_PASS}
      POSTGRES_DB: ${SUPER_ADMIN_DB}

      # Application DB + user (used by our init script)
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}


    ports:
      # host:container → Postgres accessible on localhost:2074
      - "2074:5432"
    volumes:
      # Persist only the actual data directory (recommended)
      - postgres_data:/var/lib/postgresql
      # Run any init SQL scripts (create app user, etc.)
      - ./init-scripts:/docker-entrypoint-initdb.d

      - ./uploads:/app/uploads
    networks:
      - social-soko-net

  email_worker:
    build: 
      context: .
      dockerfile: workers/Dockerfile.worker
    container_name: email-worker
    env_file:
      - .env.development
    environment:
      NODE_ENV: development
    depends_on:
      - postgres
    networks:
      - social-soko-net
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: social-soko-api
    env_file:
      - .env.development
    environment:
      NODE_ENV: development
    ports:
      - "2078:2078"
    depends_on:
      - postgres
    volumes:
      # Your source code (live edits on host)
      - .:/usr/src/app
      # Keep node_modules inside container so host OS doesn’t conflict
      - /usr/src/app/node_modules
    networks:
      - social-soko-net

  nocodb:
    image: nocodb/nocodb:latest
    container_name: nocodb
    restart: unless-stopped
    ports:
      - "2079:8080"
    volumes:
      - ./nocodb:/usr/app/data
    environment:
      NC_DB: "pg://postgres:5432?u=${DB_USER}&p=${DB_PASS}&d=nocodb_meta"
      NC_AUTH_JWT_SECRET: "569a1821-0a93-45e8-87ab-eb857f20a010"
      NC_ALLOW_LOCAL_EXTERNAL_DBS: "true"
    depends_on:
      - postgres
    networks:
      - social-soko-net

networks:
  social-soko-net:
    name: social-soko-net
    driver: bridge

volumes:
  postgres_data:
