# backend/Dockerfile.dev

FROM node:22-alpine

# Create app directory
WORKDIR /usr/src/app

# Create uploads folder

RUN mkdir -p uploads/logos

# Install dependencies
COPY package.json package-lock.json*  yarn.lock* ./

RUN \
    if [ - f package-lock.json]; then npm ci; \
    elif [-f yarn.lock]; then yarn install; \
    else npm install; \
    fi


# Copy the rest of the source
COPY . .


# Expose the backend port
EXPOSE 2070

# Defaul dev command
CMD ["npm", "run", "dev"]