FROM node:22-alpine

WORKDIR /usr/src/app

# Install dependencies
COPY package.json package-lock.json* yarn.lock* ./

RUN \
    if [ -f package-lock.json ]; then npm install; \
    elif [ -f yarn.lock ]; then yarn install; \
    else npm install; \
    fi

# Copy entire backend (so worker has access to models/services)
COPY . .

# Workers don't expose ports
CMD ["node", "workers/emailWorker.js"]
