// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/logout": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/forgot-password": {
    params: {};
  };
  "/reset-password": {
    params: {};
  };
  "/verify-email": {
    params: {};
  };
  "/posts/:postId": {
    params: {
      "postId": string;
    };
  };
  "/posts/new-post": {
    params: {};
  };
  "/business": {
    params: {};
  };
  "/business/create-business": {
    params: {};
  };
  "/business/join": {
    params: {};
  };
  "/business/:businessId": {
    params: {
      "businessId": string;
    };
  };
  "/business/:businessId/profile": {
    params: {
      "businessId": string;
    };
  };
  "/business-memberships/:businessId": {
    params: {
      "businessId": string;
    };
  };
  "/business-memberships/:businessId/requests": {
    params: {
      "businessId": string;
    };
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/login" | "/logout" | "/register" | "/forgot-password" | "/reset-password" | "/verify-email" | "/posts/:postId" | "/posts/new-post" | "/business" | "/business/create-business" | "/business/join" | "/business/:businessId" | "/business/:businessId/profile" | "/business-memberships/:businessId" | "/business-memberships/:businessId/requests";
  };
  "routes/_index.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "./routes/auth/login.jsx": {
    id: "routes/auth/login";
    page: "/login";
  };
  "routes/auth/logout.jsx": {
    id: "routes/auth/logout";
    page: "/logout";
  };
  "./routes/auth/register.jsx": {
    id: "routes/auth/register";
    page: "/register";
  };
  "./routes/auth/forgot-password.jsx": {
    id: "routes/auth/forgot-password";
    page: "/forgot-password";
  };
  "./routes/auth/reset-password.jsx": {
    id: "routes/auth/reset-password";
    page: "/reset-password";
  };
  "./routes/auth/verify-email.jsx": {
    id: "routes/auth/verify-email";
    page: "/verify-email";
  };
  "routes/pages/$postId.jsx": {
    id: "routes/pages/$postId";
    page: "/posts/:postId";
  };
  "routes/pages/create-post.jsx": {
    id: "routes/pages/create-post";
    page: "/posts/new-post";
  };
  "routes/business/layout.jsx": {
    id: "routes/business/layout";
    page: "/business" | "/business/create-business" | "/business/join" | "/business/:businessId" | "/business/:businessId/profile";
  };
  "routes/business/my-businesses.jsx": {
    id: "routes/business/my-businesses";
    page: "/business";
  };
  "routes/business/create-business.jsx": {
    id: "routes/business/create-business";
    page: "/business/create-business";
  };
  "routes/business/search.jsx": {
    id: "routes/business/search";
    page: "/business/join";
  };
  "routes/business/$businessId.jsx": {
    id: "routes/business/$businessId";
    page: "/business/:businessId";
  };
  "routes/business/profile.jsx": {
    id: "routes/business/profile";
    page: "/business/:businessId/profile";
  };
  "routes/businessMemberships/layout.jsx": {
    id: "routes/businessMemberships/layout";
    page: "/business-memberships/:businessId" | "/business-memberships/:businessId/requests";
  };
  "routes/businessMemberships/index.jsx": {
    id: "routes/businessMemberships/index";
    page: "/business-memberships/:businessId";
  };
  "routes/businessMemberships/requests.jsx": {
    id: "routes/businessMemberships/requests";
    page: "/business-memberships/:businessId/requests";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/_index": typeof import("./app/routes/_index.jsx");
  "routes/auth/login": typeof import("./app/./routes/auth/login.jsx");
  "routes/auth/logout": typeof import("./app/routes/auth/logout.jsx");
  "routes/auth/register": typeof import("./app/./routes/auth/register.jsx");
  "routes/auth/forgot-password": typeof import("./app/./routes/auth/forgot-password.jsx");
  "routes/auth/reset-password": typeof import("./app/./routes/auth/reset-password.jsx");
  "routes/auth/verify-email": typeof import("./app/./routes/auth/verify-email.jsx");
  "routes/pages/$postId": typeof import("./app/routes/pages/$postId.jsx");
  "routes/pages/create-post": typeof import("./app/routes/pages/create-post.jsx");
  "routes/business/layout": typeof import("./app/routes/business/layout.jsx");
  "routes/business/my-businesses": typeof import("./app/routes/business/my-businesses.jsx");
  "routes/business/create-business": typeof import("./app/routes/business/create-business.jsx");
  "routes/business/search": typeof import("./app/routes/business/search.jsx");
  "routes/business/$businessId": typeof import("./app/routes/business/$businessId.jsx");
  "routes/business/profile": typeof import("./app/routes/business/profile.jsx");
  "routes/businessMemberships/layout": typeof import("./app/routes/businessMemberships/layout.jsx");
  "routes/businessMemberships/index": typeof import("./app/routes/businessMemberships/index.jsx");
  "routes/businessMemberships/requests": typeof import("./app/routes/businessMemberships/requests.jsx");
};